### ISSUE TITLE
Appropriately generate library

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/mauikit-filebrowsing#1]
Currently, this package compiles the source into the library `libMauiKitFileBrowsing.so.2.0.0`; however, this library _does not compile correctly_ because of an issue with ECM 5.84.0 ([see this issue](https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/150)). The problem mentioned in that link is (I believe) going to be fixed in version 5.85.0 of ECM.

The library compiles correctly when the source is compiled locally, ~~and the CMake flag `-DENABLE_BSYMBOLICFUNCTIONS=OFF` is used. Nonetheless, that's not the case when creating the package in Travis~~. The library generated in Travis is 966K in size, while a locally generated build generates a 9.6MiB file.

I have attempted to add an override to `dh_auto_configure` to no avail (multiple times, using at least a dozen combinations of commands), and thus far, I'm at a complete loss as to how `debhelper` works.

The current workaround (which I _understand is very *wrong*_) is to download a correctly compiled library and overwrite the file provided in the package using the `postinst` script.

Anyway, this is a *bug* with this package.

**Comment by milohr** [comment]
To build locally it is not needed to add the flag to disable symbolic functions.
The issue is coming from the ECM used to build the library
